#!/bin/sh

set -e

cat > input.blob

JSON_TEMPLATE="$(echo "$2" | jq -c '{ filename: .filename, contentType: "application/pdf", languageCode: .languageCode, wantOcr: false, wantSplitByPage: false, metadata: .metadata }')"

if [ 'true' = $(echo "$2" | jq .wantSplitByPage) ]; then
  exec /app/split-and-extract-pdf "$1" "$JSON_TEMPLATE"
else
  exec /app/extract-pdf "$1" "$JSON_TEMPLATE"
fi
